### ISSUE TITLE
スケジュール

### ISSUE THREAD

**Issue by shizunaito** [shizunaito/rails-tutorial-1#2]
## 目的
全体のスケジュール感と進捗を確認する

## やること
- とりあえずスケジュール決めます
- 適宜変更してコメントします

## とりあえずスケジュール

6/21　第1章
6/22　第1章〜第2章
6/23　第3章

6/26　第4章〜第5章
6/27　第6章
6/28　第7章
6/29　第8章
6/30　第9章

7/3　第10章
7/4　第10章（続き）
7/5　第11章
7/6　第11章（続き）
7/7　第12章

7/10　第13章
7/11　第13章（続き）
7/12　第14章
7/13　第14章（続き）
7/14　復習とか

7/17〜　API

**Comment by Asuforce** [comment]
:nicetry:

**Comment by shizunaito** [comment]
作業リポジトリが変わったのでCloseして移行します
